### ISSUE TITLE
Changes to SelectionCriteria are not reflected in the related Subscription Filter

### ISSUE THREAD

**Issue by jrdeck** [aws-cloudformation/aws-cloudformation-resource-providers-logs#111]
I have deployed 

```
Parameters:
  DestinationArn:
    Type: String
    Description: "ARN of the aggregator Logs Destination."
    Default: 'arn:aws:logs:<region>:<acct id>:destination:CWLtoFirehoseDestination'

  FilterPattern:
    Type: String
    Description: "Specify a CloudWatch Filter Pattern to whitelist what is ingested. Leave blank for 'ingest everything'."
    Default: ''

  ExcludeLogGroups:
    Type: CommaDelimitedList
    Description: "Comma delimited list of Log Groups to EXCLUDE from ingestion."
    Default: '"foo","bar","/aws/vpc/flow-logs"'

  CWLtoCentralLoggingAccountPolicy:
    UpdateReplacePolicy: Delete
    Type: AWS::Logs::AccountPolicy
    DeletionPolicy: Delete
    DependsOn: CWLtoCentralLoggingFirehoseDestinationRole
    Properties:
      PolicyType: SUBSCRIPTION_FILTER_POLICY
      PolicyDocument: !Sub '{"RoleArn":"arn:aws:iam::${AWS::AccountId}:role/CWLtoCentralLoggingFirehoseDestinationRole","DestinationArn":"${DestinationArn}","FilterPattern":"${FilterPattern}","Distribution":"Random"}'
      Scope: ALL
      PolicyName: CrossAccountFirehosePolicy
      SelectionCriteria: 
        Fn::Sub:
          - 'LogGroupName NOT IN [${ExcludeLogGroupsFormatted}]'
          -   ExcludeLogGroupsFormatted:
                Fn::Join: 
                  - ","
                  - !Ref ExcludeLogGroups
...
```

This works fine to deploy the Account Policy initially. 

If I subsequently amend the ExcludeLogGroups parameter, adding another value to the CSV list, it _looks like_ it works in the CloudFormation console (ie. shows "Success"). 

However, if I then check via the CLI:

`aws logs describe-account-policies --policy-type "SUBSCRIPTION_FILTER_POLICY"`

It still has the original selectionCriteria.

I have to completely delete the Stack and re-add it in order to apply the change. This is especially frustrating as I am using Stack Sets at an org level.
